### ISSUE TITLE
sorts/random_normal_distribution_quicksort.py has no tests

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Python#9124] opened 2023-09-29 13:43 UTC
### Repository commit

3

### Python version (python --version)

Python 3.11.5

### Dependencies version (pip freeze)

Numpy

### Expected behavior

Tests.

### Actual behavior

No tests.

**Comment by cclauss** [comment] 2023-09-29 13:46
@prateekiiest

**Comment by Dev-Arhaan** [comment] 2023-09-30 05:44
Explain a bit more about this problem. Maybe I can help.

**Comment by Avineesh28** [comment] 2023-09-30 10:19
If its regarding coming up with viable test cases and ensure running of the algortihm, I can help out!

**Comment by cclauss** [comment] 2023-09-30 13:37
Please read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) to understand what this repo requires for tests.

**Comment by cclauss** [comment] 2023-09-30 17:41
As discussed in [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md), we do NOT assign issues.  We review pull requests.

**Comment by tianyizheng02** [comment] 2023-09-30 22:07
@cclauss I think this file should be deleted entirely. It's just an implementation of quicksort with a random pivot (which we already have), and the only difference is that the _array elements_ themselves follow a normal distribution. For all intents and purposes, it's a duplicate of [sorts/random_pivot_quick_sort.py](https://github.com/TheAlgorithms/Python/blob/dec96438be1a165eaa300a4d6df33e338b4e44c6/sorts/random_pivot_quick_sort.py).

**Comment by Rohxn16** [comment] 2023-10-01 03:36
@tianyizheng02 hi, I am a beginner in open source and it is my first time contributing in a big repo like this. So I deleted the file random_normal_distribution_quicksort.py which you said is a copy of the random_pivot_quicksort.py . If I have made any mistakes please feel free to inform me, Thank you.

**Comment by tianyizheng02** [comment] 2023-10-01 05:04
Reopening this issue because I just realized that `quick_sort.py` already uses a random pivot, which means that _both_ `random_normal_distribution_quicksort.py` and `random_pivot_quick_sort.py` are duplicates and both should be deleted.

**Closed** 2023-10-01 05:21 UTC
Labels: bug, require tests
