### ISSUE TITLE
gaussian function in maths/gaussian.py seems wrong

### ISSUE THREAD

**Issue by kunl7564** [TheAlgorithms/Python#1375] opened 2019-10-16 08:17 UTC
1 / sqrt(2 * pi * sigma ** 2) * exp(-(x - mu) ** 2 / 2 * sigma ** 2)

should be

1 / sqrt(2 * pi * sigma ** 2) * exp(-(x - mu) ** 2 /( 2 * sigma ** 2))

**Comment by BenSandeen** [comment] 2019-10-16 13:36
According to Wikipedia [https://en.wikipedia.org/wiki/Gaussian_function](url), the current representation looks correct to me.  I think it would make sense to pull both of the `** 2` out of the exponential and just put them outside the parentheses, like this:

`1 / sqrt(2 * pi * sigma ** 2) * exp(-1 / 2 * ((x - mu) / sigma) ** 2)`

**Comment by cclauss** [comment] 2019-10-17 14:25
Could you please write a doctest for the failing usecase?  Please read CONTRIBUTING.md for details.

**Comment by kunl7564** [comment] 2019-10-21 08:36
I notice that this issue has already been fixed in https://github.com/TheAlgorithms/Python/commit/f6bd8c95c05ca7c74e534d9e7c13ebab558fb8d0

Not sure if there is still something I can help.

**Comment by darkmatter18** [comment] 2019-12-07 15:39
Hi, @kunl7564 I tested the algorithm for both
1. `1 / sqrt(2 * pi * sigma ** 2) * exp(-(x - mu) ** 2 / 2 * sigma ** 2)`
2 . `1 / sqrt(2 * pi * sigma ** 2) * exp(-(x - mu) ** 2 /( 2 * sigma ** 2))`

Both seem to produce the same output. I think the issue is not actually an issue.

**Comment by cclauss** [comment] 2019-12-07 15:50
Already been fixed in f6bd8c9

**Closed by cclauss** 2019-12-07 15:50 UTC
